title: Soufiane's Portfolio
description: Personal portfolio showcasing skills and projects
baseurl: "/Portfolio"
url: "https://soufiane1boutouil.github.io"
theme: jekyll-theme-minimal
scripts:
  - js/script.js
